spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/after}
spring.datasource.username=${DB_USERNAME:after}
spring.datasource.password=${DB_PASSWORD:after}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info